CREATE TABLE IF NOT EXISTS users ( 
  id INTEGER PRIMARY KEY AUTOINCREMENT, 
  username TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS exercises ( 
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  description TEXT NOT NULL,
  duration INTEGER NOT NULL,
  date TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);